const std = @import("std");
const assert = std.debug.assert;
const Ast = std.zig.Ast;
const Token = std.zig.Token;
const zig_ast = @import("zig_ast");
const ExternEnum = zig_ast.ExternEnum;
const ExternStruct = zig_ast.ExternStruct;
const comptimeCamelToSnakeCase = zig_ast.comptimeCamelToSnakeCase;

const rust_keywords = std.StaticStringMap(void).initComptime(.{
    .{"as"},
    .{"extern"},
    .{"mod"},
});

pub fn main() !void {
    var arena_state = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    const args = try std.process.argsAlloc(arena);
    assert(args.len == 3);
    const enums_path = args[1];
    const full_path = args[2];

    var enums_file = try std.fs.cwd().createFile(enums_path, .{});
    defer enums_file.close();
    var enums_file_buffer: [4096]u8 = undefined;
    var enums_file_writer = enums_file.writer(&enums_file_buffer);
    const enums_writer = &enums_file_writer.interface;
    defer enums_writer.flush() catch @panic("flush failed");

    try enums_writer.writeAll(
        \\//! This file is auto-generated by generate_rust.zig.
        \\
        \\use super::*;
        \\
    );

    try writeEnum(arena, enums_writer, Token.Tag, null);
    try writeEnum(arena, enums_writer, Ast.Node.Tag, "See https://ziglang.org/documentation/0.15.2/std/#std.zig.Ast.Node.Tag");
    try writeEnum(arena, enums_writer, std.builtin.Type.Pointer.Size, null);
    try writeEnum(arena, enums_writer, std.zig.BuiltinFn.Tag, null);

    var lifetimes: std.StringArrayHashMapUnmanaged(void) = .empty;
    // TODO: either (a) rename output file or (b) move this struct to a different file
    try writeStruct(arena, enums_writer, Ast.Location, &lifetimes);

    var full_file = try std.fs.cwd().createFile(full_path, .{});
    defer full_file.close();
    var full_file_buffer: [4096]u8 = undefined;
    var full_file_writer = full_file.writer(&full_file_buffer);
    const full_writer = &full_file_writer.interface;
    defer full_writer.flush() catch @panic("flush failed");

    try full_writer.writeAll(
        \\//! This file is auto-generated by generate_rust.zig.
        \\
        \\use std::mem::MaybeUninit;
        \\
        \\use super::*;
        \\
    );

    inline for (comptime std.meta.declarations(Ast.full)) |decl| {
        try writeFull(arena, full_writer, decl.name);
    }
}

fn toRustType(comptime T: type) struct { []const u8, ?[]const u8 } {
    @setEvalBranchQuota(10_000);
    return switch (T) {
        bool => .{ "bool", null },

        u32 => .{ "TokenIndex", null },

        [*]const ExternEnum(Ast.Node.Index) => .{ "*const NodeIndex", null },
        usize => .{ "usize", null },

        ExternEnum(Token.Tag) => .{ "TokenTag", null },
        ExternEnum(Ast.Node.Tag) => .{ "NodeTag", null },
        ExternEnum(std.builtin.Type.Pointer.Size) => .{ "PointerSize", null },
        ExternEnum(std.zig.BuiltinFn.Tag) => .{ "BuiltinFnTag", null },

        ExternEnum(Ast.OptionalTokenIndex) => .{ "OptionalTokenIndex", null },
        ExternEnum(Ast.Node.Index) => .{ "NodeIndex", null },
        ExternEnum(Ast.Node.OptionalIndex) => .{ "OptionalNodeIndex", null },

        ExternStruct(Ast.Location) => .{ "Location", null },

        ExternStruct(Ast.full.VarDecl) => .{ "VarDecl", null },
        ExternStruct(Ast.full.AssignDestructure) => .{ "AssignDestructure", null },
        ExternStruct(Ast.full.If) => .{ "If", null },
        ExternStruct(Ast.full.While) => .{ "While", null },
        ExternStruct(Ast.full.For) => .{ "For", null },
        ExternStruct(Ast.full.ContainerField) => .{ "ContainerField", null },
        ExternStruct(Ast.full.FnProto) => .{ "FnProto", null },
        ExternStruct(Ast.full.StructInit) => .{ "StructInit", null },
        ExternStruct(Ast.full.ArrayInit) => .{ "ArrayInit", null },
        ExternStruct(Ast.full.ArrayType) => .{ "ArrayType", null },
        ExternStruct(Ast.full.PtrType) => .{ "PtrType", null },
        ExternStruct(Ast.full.Slice) => .{ "Slice", null },
        ExternStruct(Ast.full.ContainerDecl) => .{ "ContainerDecl", null },
        ExternStruct(Ast.full.Switch) => .{ "Switch", null },
        ExternStruct(Ast.full.SwitchCase) => .{ "SwitchCase", null },
        ExternStruct(Ast.full.Asm) => .{ "Asm", null },
        ExternStruct(Ast.full.Call) => .{ "Call", null },

        ExternStruct(Ast.full.VarDecl.Components) => .{ "VarDeclComponents", null },
        ExternStruct(Ast.full.AssignDestructure.Components) => .{ "AssignDestructureComponents", "ast" },
        ExternStruct(Ast.full.If.Components) => .{ "IfComponents", null },
        ExternStruct(Ast.full.While.Components) => .{ "WhileComponents", null },
        ExternStruct(Ast.full.For.Components) => .{ "ForComponents", "ast" },
        ExternStruct(Ast.full.ContainerField.Components) => .{ "ContainerFieldComponents", null },
        ExternStruct(Ast.full.FnProto.Components) => .{ "FnProtoComponents", "ast" },
        ExternStruct(Ast.full.StructInit.Components) => .{ "StructInitComponents", "ast" },
        ExternStruct(Ast.full.ArrayInit.Components) => .{ "ArrayInitComponents", "ast" },
        ExternStruct(Ast.full.ArrayType.Components) => .{ "ArrayTypeComponents", null },
        ExternStruct(Ast.full.PtrType.Components) => .{ "PtrTypeComponents", null },
        ExternStruct(Ast.full.Slice.Components) => .{ "SliceComponents", null },
        ExternStruct(Ast.full.ContainerDecl.Components) => .{ "ContainerDeclComponents", "ast" },
        ExternStruct(Ast.full.Switch.Components) => .{ "SwitchComponents", "ast" },
        ExternStruct(Ast.full.SwitchCase.Components) => .{ "SwitchCaseComponents", "ast" },
        ExternStruct(Ast.full.Asm.Components) => .{ "AsmComponents", "ast" },
        ExternStruct(Ast.full.Call.Components) => .{ "CallComponents", "ast" },

        else => @panic("unsupported type: " ++ @typeName(T)),
    };
}

fn writeFull(
    arena: std.mem.Allocator,
    writer: *std.io.Writer,
    comptime name: []const u8,
) !void {
    if (comptime std.mem.eql(u8, name, "AsmLegacy")) return;
    const T = @field(Ast.full, name);
    var lifetimes: std.StringArrayHashMapUnmanaged(void) = .empty;
    try writeStruct(arena, writer, T, &lifetimes);
    var temp: std.StringArrayHashMapUnmanaged(void) = .empty;
    try writeStruct(arena, writer, T.Components, &temp);
    if (comptime std.mem.eql(u8, name, "AssignDestructure")) {
        return;
    }
    try writeFullImpl(arena, writer, name, lifetimes.keys());
}

fn writeFullImpl(
    arena: std.mem.Allocator,
    writer: *std.io.Writer,
    comptime name: []const u8,
    lifetimes: []const []const u8,
) !void {
    const T = @field(Ast.full, name);
    const fullT = @field(Ast, "full" ++ name);
    const FullT = @TypeOf(fullT);
    const fn_info = @typeInfo(FullT).@"fn";
    assert(fn_info.return_type == ?T);

    comptime var param_types: [fn_info.params.len]type = undefined;
    inline for (&param_types, fn_info.params) |*param_type, param|
        param_type.* = param.type.?;

    const buffer_size: usize =
        if (comptime std.mem.eql(type, &param_types, &.{ Ast, Ast.Node.Index }))
            0
        else if (comptime std.mem.eql(type, &param_types, &.{ Ast, *[1]Ast.Node.Index, Ast.Node.Index }))
            1
        else if (comptime std.mem.eql(type, &param_types, &.{ Ast, *[2]Ast.Node.Index, Ast.Node.Index }))
            2
        else
            comptime unreachable;

    const lifetimes_str = try lifetimesToStr(arena, lifetimes);

    try writer.writeByte('\n');

    if (lifetimes.len > 0) {
        try writer.print("impl{2s} Full<'ast, {0d}> for {1s}{2s} {{\n", .{ buffer_size, name, lifetimes_str });
    } else {
        assert(buffer_size == 0);
        try writer.print("impl Full<'_, {0d}> for {1s} {{\n", .{ buffer_size, name });
    }

    if (buffer_size == 0) {
        try writer.print(
            \\    unsafe fn from(
            \\        tree: *const Ast,
            \\        _buffer: *mut [NodeIndex; {0d}],
            \\        index: NodeIndex,
            \\    ) -> Option<Self> {{
            \\        let mut full_{2s} = MaybeUninit::uninit();
            \\        unsafe {{
            \\            if zig_ast_full_{2s}(tree, index, full_{2s}.as_mut_ptr()) {{
            \\                Some(full_{2s}.assume_init())
            \\            }} else {{
            \\                None
            \\            }}
            \\        }}
            \\    }}
            \\}}
            \\
            \\unsafe extern "C" {{
            \\    fn zig_ast_full_{2s}(
            \\        tree: *const Ast,
            \\        index: NodeIndex,
            \\        full_{2s}: *mut {1s},
            \\    ) -> bool;
            \\}}
            \\
        , .{ buffer_size, name, comptimeCamelToSnakeCase(name) });
    } else {
        try writer.print(
            \\    unsafe fn from(
            \\        tree: *const Ast,
            \\        buffer: *mut [NodeIndex; {0d}],
            \\        index: NodeIndex,
            \\    ) -> Option<Self> {{
            \\        let mut full_{2s} = MaybeUninit::uninit();
            \\        unsafe {{
            \\            if zig_ast_full_{2s}(tree, buffer, index, full_{2s}.as_mut_ptr()) {{
            \\                Some(full_{2s}.assume_init())
            \\            }} else {{
            \\                None
            \\            }}
            \\        }}
            \\    }}
            \\}}
            \\
            \\unsafe extern "C" {{
            \\    fn zig_ast_full_{2s}(
            \\        tree: *const Ast,
            \\        buffer: *mut [NodeIndex; {0d}],
            \\        index: NodeIndex,
            \\        full_{2s}: *mut {1s},
            \\    ) -> bool;
            \\}}
            \\
        , .{ buffer_size, name, comptimeCamelToSnakeCase(name) });
    }

    try writer.flush();
}

fn lifetimesToStr(arena: std.mem.Allocator, lifetimes: []const []const u8) ![]const u8 {
    var buffer: std.ArrayList(u8) = .empty;
    if (lifetimes.len == 0)
        return "";
    try buffer.append(arena, '<');
    for (lifetimes, 0..) |name, i| {
        if (i > 0) try buffer.appendSlice(arena, ", ");
        try buffer.append(arena, '\'');
        try buffer.appendSlice(arena, name);
    }
    try buffer.append(arena, '>');
    return buffer.items;
}

fn writeStruct(
    arena: std.mem.Allocator,
    writer: *std.io.Writer,
    comptime T: type,
    lifetimes: *std.StringArrayHashMapUnmanaged(void),
) !void {
    @setEvalBranchQuota(100_000);
    const Struct = ExternStruct(T);
    const fields = @typeInfo(Struct).@"struct".fields;
    const struct_name, const struct_lifetime = comptime toRustType(Struct);

    try lifetimes.ensureUnusedCapacity(arena, 1 + fields.len);
    if (struct_lifetime) |name|
        lifetimes.putAssumeCapacity(name, {});
    inline for (fields) |field| {
        _, const type_lifetime = toRustType(field.type);
        if (type_lifetime) |name|
            lifetimes.putAssumeCapacity(name, {});
    }

    const lifetimes_str = try lifetimesToStr(arena, lifetimes.keys());

    try writer.writeByte('\n');

    try writer.print(
        \\#[repr(C)]
        \\pub struct {s}{s} {{
        \\
    , .{ struct_name, lifetimes_str });

    inline for (fields) |field| {
        const type_name, const type_lifetime = toRustType(field.type);
        try writer.print("    pub {s}: {s}", .{ field.name, type_name });
        if (type_lifetime) |name|
            try writer.print("<'{s}>", .{name});
        try writer.writeAll(",\n");
    }

    if (struct_lifetime) |name|
        try writer.print("    _marker: PhantomData<&'{s} ()>,\n", .{name});

    try writer.writeAll("}\n");
    try writer.flush();
}

fn toRustInt(arena: std.mem.Allocator, comptime T: type) ![]const u8 {
    const info = @typeInfo(T).int;
    const bits = info.bits;
    const signedness = switch (info.signedness) {
        .signed => 'i',
        .unsigned => 'u',
    };
    return try std.fmt.allocPrint(arena, "{c}{d}", .{ signedness, bits });
}

fn writeEnum(
    arena: std.mem.Allocator,
    writer: *std.io.Writer,
    comptime T: type,
    doc_comment: ?[]const u8,
) !void {
    const Enum = ExternEnum(T);
    const Tag = @typeInfo(Enum).@"enum".tag_type;
    const rs_name, const lifetime = toRustType(Enum);
    assert(lifetime == null);

    try writer.writeByte('\n');

    if (doc_comment) |s|
        try writer.print("/// {s}\n", .{s});

    if (T == std.zig.BuiltinFn.Tag)
        try writer.writeAll("#[allow(non_camel_case_types)]\n");

    try writer.print(
        \\#[repr({s})]
        \\#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
        \\pub enum {s} {{
        \\
    , .{ try toRustInt(arena, Tag), rs_name });

    for (std.meta.tags(Enum)) |tag| {
        const tag_name = @tagName(tag);
        const rs_tag_name = switch (T) {
            std.zig.BuiltinFn.Tag => if (rust_keywords.has(tag_name)) try std.fmt.allocPrint(arena, "r#{s}", .{tag_name}) else tag_name,
            else => try snakeToCamelCase(arena, tag_name),
        };
        try writer.print("    {s} = {d},\n", .{ rs_tag_name, @intFromEnum(tag) });
    }

    try writer.writeAll("}\n");
    try writer.flush();
}

fn snakeToCamelCase(arena: std.mem.Allocator, name: []const u8) ![]const u8 {
    var bytes: std.ArrayList(u8) = .empty;
    var it = std.mem.splitScalar(u8, name, '_');
    while (it.next()) |s| {
        try bytes.append(arena, std.ascii.toUpper(s[0]));
        try bytes.appendSlice(arena, s[1..]);
    }
    return bytes.items;
}
