//! This file is auto-generated by generate_rust.zig.

use std::mem::MaybeUninit;

use super::*;

#[repr(C)]
pub struct VarDecl {
    pub visib_token: OptionalTokenIndex,
    pub extern_export_token: OptionalTokenIndex,
    pub lib_name: OptionalTokenIndex,
    pub threadlocal_token: OptionalTokenIndex,
    pub comptime_token: OptionalTokenIndex,
    pub ast: VarDeclComponents,
}

#[repr(C)]
pub struct VarDeclComponents {
    pub mut_token: TokenIndex,
    pub type_node: OptionalNodeIndex,
    pub align_node: OptionalNodeIndex,
    pub addrspace_node: OptionalNodeIndex,
    pub section_node: OptionalNodeIndex,
    pub init_node: OptionalNodeIndex,
}

impl Full<'_, 0> for VarDecl {
    unsafe fn from(
        tree: *const Ast,
        _buffer: *mut [NodeIndex; 0],
        index: NodeIndex,
    ) -> Option<Self> {
        let mut full_var_decl = MaybeUninit::uninit();
        unsafe {
            if zig_ast_full_var_decl(tree, index, full_var_decl.as_mut_ptr()) {
                Some(full_var_decl.assume_init())
            } else {
                None
            }
        }
    }
}

unsafe extern "C" {
    fn zig_ast_full_var_decl(
        tree: *const Ast,
        index: NodeIndex,
        full_var_decl: *mut VarDecl,
    ) -> bool;
}

#[repr(C)]
pub struct AssignDestructure<'ast> {
    pub comptime_token: OptionalTokenIndex,
    pub ast: AssignDestructureComponents<'ast>,
}

#[repr(C)]
pub struct AssignDestructureComponents<'ast> {
    pub variables_ptr: *const NodeIndex,
    pub variables_len: usize,
    pub equal_token: TokenIndex,
    pub value_expr: NodeIndex,
    _marker: PhantomData<&'ast ()>,
}

#[repr(C)]
pub struct If {
    pub payload_token: OptionalTokenIndex,
    pub error_token: OptionalTokenIndex,
    pub else_token: TokenIndex,
    pub ast: IfComponents,
}

#[repr(C)]
pub struct IfComponents {
    pub if_token: TokenIndex,
    pub cond_expr: NodeIndex,
    pub then_expr: NodeIndex,
    pub else_expr: OptionalNodeIndex,
}

impl Full<'_, 0> for If {
    unsafe fn from(
        tree: *const Ast,
        _buffer: *mut [NodeIndex; 0],
        index: NodeIndex,
    ) -> Option<Self> {
        let mut full_if = MaybeUninit::uninit();
        unsafe {
            if zig_ast_full_if(tree, index, full_if.as_mut_ptr()) {
                Some(full_if.assume_init())
            } else {
                None
            }
        }
    }
}

unsafe extern "C" {
    fn zig_ast_full_if(
        tree: *const Ast,
        index: NodeIndex,
        full_if: *mut If,
    ) -> bool;
}

#[repr(C)]
pub struct While {
    pub ast: WhileComponents,
    pub inline_token: OptionalTokenIndex,
    pub label_token: OptionalTokenIndex,
    pub payload_token: OptionalTokenIndex,
    pub error_token: OptionalTokenIndex,
    pub else_token: TokenIndex,
}

#[repr(C)]
pub struct WhileComponents {
    pub while_token: TokenIndex,
    pub cond_expr: NodeIndex,
    pub cont_expr: OptionalNodeIndex,
    pub then_expr: NodeIndex,
    pub else_expr: OptionalNodeIndex,
}

impl Full<'_, 0> for While {
    unsafe fn from(
        tree: *const Ast,
        _buffer: *mut [NodeIndex; 0],
        index: NodeIndex,
    ) -> Option<Self> {
        let mut full_while = MaybeUninit::uninit();
        unsafe {
            if zig_ast_full_while(tree, index, full_while.as_mut_ptr()) {
                Some(full_while.assume_init())
            } else {
                None
            }
        }
    }
}

unsafe extern "C" {
    fn zig_ast_full_while(
        tree: *const Ast,
        index: NodeIndex,
        full_while: *mut While,
    ) -> bool;
}

#[repr(C)]
pub struct For<'ast> {
    pub ast: ForComponents<'ast>,
    pub inline_token: OptionalTokenIndex,
    pub label_token: OptionalTokenIndex,
    pub payload_token: TokenIndex,
    pub else_token: OptionalTokenIndex,
}

#[repr(C)]
pub struct ForComponents<'ast> {
    pub for_token: TokenIndex,
    pub inputs_ptr: *const NodeIndex,
    pub inputs_len: usize,
    pub then_expr: NodeIndex,
    pub else_expr: OptionalNodeIndex,
    _marker: PhantomData<&'ast ()>,
}

impl<'ast> Full<'ast, 0> for For<'ast> {
    unsafe fn from(
        tree: *const Ast,
        _buffer: *mut [NodeIndex; 0],
        index: NodeIndex,
    ) -> Option<Self> {
        let mut full_for = MaybeUninit::uninit();
        unsafe {
            if zig_ast_full_for(tree, index, full_for.as_mut_ptr()) {
                Some(full_for.assume_init())
            } else {
                None
            }
        }
    }
}

unsafe extern "C" {
    fn zig_ast_full_for(
        tree: *const Ast,
        index: NodeIndex,
        full_for: *mut For,
    ) -> bool;
}

#[repr(C)]
pub struct ContainerField {
    pub comptime_token: OptionalTokenIndex,
    pub ast: ContainerFieldComponents,
}

#[repr(C)]
pub struct ContainerFieldComponents {
    pub main_token: TokenIndex,
    pub type_expr: OptionalNodeIndex,
    pub align_expr: OptionalNodeIndex,
    pub value_expr: OptionalNodeIndex,
    pub tuple_like: bool,
}

impl Full<'_, 0> for ContainerField {
    unsafe fn from(
        tree: *const Ast,
        _buffer: *mut [NodeIndex; 0],
        index: NodeIndex,
    ) -> Option<Self> {
        let mut full_container_field = MaybeUninit::uninit();
        unsafe {
            if zig_ast_full_container_field(tree, index, full_container_field.as_mut_ptr()) {
                Some(full_container_field.assume_init())
            } else {
                None
            }
        }
    }
}

unsafe extern "C" {
    fn zig_ast_full_container_field(
        tree: *const Ast,
        index: NodeIndex,
        full_container_field: *mut ContainerField,
    ) -> bool;
}

#[repr(C)]
pub struct FnProto<'ast> {
    pub visib_token: OptionalTokenIndex,
    pub extern_export_inline_token: OptionalTokenIndex,
    pub lib_name: OptionalTokenIndex,
    pub name_token: OptionalTokenIndex,
    pub lparen: TokenIndex,
    pub ast: FnProtoComponents<'ast>,
}

#[repr(C)]
pub struct FnProtoComponents<'ast> {
    pub proto_node: NodeIndex,
    pub fn_token: TokenIndex,
    pub return_type: OptionalNodeIndex,
    pub params_ptr: *const NodeIndex,
    pub params_len: usize,
    pub align_expr: OptionalNodeIndex,
    pub addrspace_expr: OptionalNodeIndex,
    pub section_expr: OptionalNodeIndex,
    pub callconv_expr: OptionalNodeIndex,
    _marker: PhantomData<&'ast ()>,
}

impl<'ast> Full<'ast, 1> for FnProto<'ast> {
    unsafe fn from(
        tree: *const Ast,
        buffer: *mut [NodeIndex; 1],
        index: NodeIndex,
    ) -> Option<Self> {
        let mut full_fn_proto = MaybeUninit::uninit();
        unsafe {
            if zig_ast_full_fn_proto(tree, buffer, index, full_fn_proto.as_mut_ptr()) {
                Some(full_fn_proto.assume_init())
            } else {
                None
            }
        }
    }
}

unsafe extern "C" {
    fn zig_ast_full_fn_proto(
        tree: *const Ast,
        buffer: *mut [NodeIndex; 1],
        index: NodeIndex,
        full_fn_proto: *mut FnProto,
    ) -> bool;
}

#[repr(C)]
pub struct StructInit<'ast> {
    pub ast: StructInitComponents<'ast>,
}

#[repr(C)]
pub struct StructInitComponents<'ast> {
    pub lbrace: TokenIndex,
    pub fields_ptr: *const NodeIndex,
    pub fields_len: usize,
    pub type_expr: OptionalNodeIndex,
    _marker: PhantomData<&'ast ()>,
}

impl<'ast> Full<'ast, 2> for StructInit<'ast> {
    unsafe fn from(
        tree: *const Ast,
        buffer: *mut [NodeIndex; 2],
        index: NodeIndex,
    ) -> Option<Self> {
        let mut full_struct_init = MaybeUninit::uninit();
        unsafe {
            if zig_ast_full_struct_init(tree, buffer, index, full_struct_init.as_mut_ptr()) {
                Some(full_struct_init.assume_init())
            } else {
                None
            }
        }
    }
}

unsafe extern "C" {
    fn zig_ast_full_struct_init(
        tree: *const Ast,
        buffer: *mut [NodeIndex; 2],
        index: NodeIndex,
        full_struct_init: *mut StructInit,
    ) -> bool;
}

#[repr(C)]
pub struct ArrayInit<'ast> {
    pub ast: ArrayInitComponents<'ast>,
}

#[repr(C)]
pub struct ArrayInitComponents<'ast> {
    pub lbrace: TokenIndex,
    pub elements_ptr: *const NodeIndex,
    pub elements_len: usize,
    pub type_expr: OptionalNodeIndex,
    _marker: PhantomData<&'ast ()>,
}

impl<'ast> Full<'ast, 2> for ArrayInit<'ast> {
    unsafe fn from(
        tree: *const Ast,
        buffer: *mut [NodeIndex; 2],
        index: NodeIndex,
    ) -> Option<Self> {
        let mut full_array_init = MaybeUninit::uninit();
        unsafe {
            if zig_ast_full_array_init(tree, buffer, index, full_array_init.as_mut_ptr()) {
                Some(full_array_init.assume_init())
            } else {
                None
            }
        }
    }
}

unsafe extern "C" {
    fn zig_ast_full_array_init(
        tree: *const Ast,
        buffer: *mut [NodeIndex; 2],
        index: NodeIndex,
        full_array_init: *mut ArrayInit,
    ) -> bool;
}

#[repr(C)]
pub struct ArrayType {
    pub ast: ArrayTypeComponents,
}

#[repr(C)]
pub struct ArrayTypeComponents {
    pub lbracket: TokenIndex,
    pub elem_count: NodeIndex,
    pub sentinel: OptionalNodeIndex,
    pub elem_type: NodeIndex,
}

impl Full<'_, 0> for ArrayType {
    unsafe fn from(
        tree: *const Ast,
        _buffer: *mut [NodeIndex; 0],
        index: NodeIndex,
    ) -> Option<Self> {
        let mut full_array_type = MaybeUninit::uninit();
        unsafe {
            if zig_ast_full_array_type(tree, index, full_array_type.as_mut_ptr()) {
                Some(full_array_type.assume_init())
            } else {
                None
            }
        }
    }
}

unsafe extern "C" {
    fn zig_ast_full_array_type(
        tree: *const Ast,
        index: NodeIndex,
        full_array_type: *mut ArrayType,
    ) -> bool;
}

#[repr(C)]
pub struct PtrType {
    pub size: PointerSize,
    pub allowzero_token: OptionalTokenIndex,
    pub const_token: OptionalTokenIndex,
    pub volatile_token: OptionalTokenIndex,
    pub ast: PtrTypeComponents,
}

#[repr(C)]
pub struct PtrTypeComponents {
    pub main_token: TokenIndex,
    pub align_node: OptionalNodeIndex,
    pub addrspace_node: OptionalNodeIndex,
    pub sentinel: OptionalNodeIndex,
    pub bit_range_start: OptionalNodeIndex,
    pub bit_range_end: OptionalNodeIndex,
    pub child_type: NodeIndex,
}

impl Full<'_, 0> for PtrType {
    unsafe fn from(
        tree: *const Ast,
        _buffer: *mut [NodeIndex; 0],
        index: NodeIndex,
    ) -> Option<Self> {
        let mut full_ptr_type = MaybeUninit::uninit();
        unsafe {
            if zig_ast_full_ptr_type(tree, index, full_ptr_type.as_mut_ptr()) {
                Some(full_ptr_type.assume_init())
            } else {
                None
            }
        }
    }
}

unsafe extern "C" {
    fn zig_ast_full_ptr_type(
        tree: *const Ast,
        index: NodeIndex,
        full_ptr_type: *mut PtrType,
    ) -> bool;
}

#[repr(C)]
pub struct Slice {
    pub ast: SliceComponents,
}

#[repr(C)]
pub struct SliceComponents {
    pub sliced: NodeIndex,
    pub lbracket: TokenIndex,
    pub start: NodeIndex,
    pub end: OptionalNodeIndex,
    pub sentinel: OptionalNodeIndex,
}

impl Full<'_, 0> for Slice {
    unsafe fn from(
        tree: *const Ast,
        _buffer: *mut [NodeIndex; 0],
        index: NodeIndex,
    ) -> Option<Self> {
        let mut full_slice = MaybeUninit::uninit();
        unsafe {
            if zig_ast_full_slice(tree, index, full_slice.as_mut_ptr()) {
                Some(full_slice.assume_init())
            } else {
                None
            }
        }
    }
}

unsafe extern "C" {
    fn zig_ast_full_slice(
        tree: *const Ast,
        index: NodeIndex,
        full_slice: *mut Slice,
    ) -> bool;
}

#[repr(C)]
pub struct ContainerDecl<'ast> {
    pub layout_token: OptionalTokenIndex,
    pub ast: ContainerDeclComponents<'ast>,
}

#[repr(C)]
pub struct ContainerDeclComponents<'ast> {
    pub main_token: TokenIndex,
    pub enum_token: OptionalTokenIndex,
    pub members_ptr: *const NodeIndex,
    pub members_len: usize,
    pub arg: OptionalNodeIndex,
    _marker: PhantomData<&'ast ()>,
}

impl<'ast> Full<'ast, 2> for ContainerDecl<'ast> {
    unsafe fn from(
        tree: *const Ast,
        buffer: *mut [NodeIndex; 2],
        index: NodeIndex,
    ) -> Option<Self> {
        let mut full_container_decl = MaybeUninit::uninit();
        unsafe {
            if zig_ast_full_container_decl(tree, buffer, index, full_container_decl.as_mut_ptr()) {
                Some(full_container_decl.assume_init())
            } else {
                None
            }
        }
    }
}

unsafe extern "C" {
    fn zig_ast_full_container_decl(
        tree: *const Ast,
        buffer: *mut [NodeIndex; 2],
        index: NodeIndex,
        full_container_decl: *mut ContainerDecl,
    ) -> bool;
}

#[repr(C)]
pub struct Switch<'ast> {
    pub ast: SwitchComponents<'ast>,
    pub label_token: OptionalTokenIndex,
}

#[repr(C)]
pub struct SwitchComponents<'ast> {
    pub switch_token: TokenIndex,
    pub condition: NodeIndex,
    pub cases_ptr: *const NodeIndex,
    pub cases_len: usize,
    _marker: PhantomData<&'ast ()>,
}

impl<'ast> Full<'ast, 0> for Switch<'ast> {
    unsafe fn from(
        tree: *const Ast,
        _buffer: *mut [NodeIndex; 0],
        index: NodeIndex,
    ) -> Option<Self> {
        let mut full_switch = MaybeUninit::uninit();
        unsafe {
            if zig_ast_full_switch(tree, index, full_switch.as_mut_ptr()) {
                Some(full_switch.assume_init())
            } else {
                None
            }
        }
    }
}

unsafe extern "C" {
    fn zig_ast_full_switch(
        tree: *const Ast,
        index: NodeIndex,
        full_switch: *mut Switch,
    ) -> bool;
}

#[repr(C)]
pub struct SwitchCase<'ast> {
    pub inline_token: OptionalTokenIndex,
    pub payload_token: OptionalTokenIndex,
    pub ast: SwitchCaseComponents<'ast>,
}

#[repr(C)]
pub struct SwitchCaseComponents<'ast> {
    pub values_ptr: *const NodeIndex,
    pub values_len: usize,
    pub arrow_token: TokenIndex,
    pub target_expr: NodeIndex,
    _marker: PhantomData<&'ast ()>,
}

impl<'ast> Full<'ast, 0> for SwitchCase<'ast> {
    unsafe fn from(
        tree: *const Ast,
        _buffer: *mut [NodeIndex; 0],
        index: NodeIndex,
    ) -> Option<Self> {
        let mut full_switch_case = MaybeUninit::uninit();
        unsafe {
            if zig_ast_full_switch_case(tree, index, full_switch_case.as_mut_ptr()) {
                Some(full_switch_case.assume_init())
            } else {
                None
            }
        }
    }
}

unsafe extern "C" {
    fn zig_ast_full_switch_case(
        tree: *const Ast,
        index: NodeIndex,
        full_switch_case: *mut SwitchCase,
    ) -> bool;
}

#[repr(C)]
pub struct Asm<'ast> {
    pub ast: AsmComponents<'ast>,
    pub volatile_token: OptionalTokenIndex,
    pub outputs_ptr: *const NodeIndex,
    pub outputs_len: usize,
    pub inputs_ptr: *const NodeIndex,
    pub inputs_len: usize,
}

#[repr(C)]
pub struct AsmComponents<'ast> {
    pub asm_token: TokenIndex,
    pub template: NodeIndex,
    pub items_ptr: *const NodeIndex,
    pub items_len: usize,
    pub clobbers: OptionalNodeIndex,
    pub rparen: TokenIndex,
    _marker: PhantomData<&'ast ()>,
}

impl<'ast> Full<'ast, 0> for Asm<'ast> {
    unsafe fn from(
        tree: *const Ast,
        _buffer: *mut [NodeIndex; 0],
        index: NodeIndex,
    ) -> Option<Self> {
        let mut full_asm = MaybeUninit::uninit();
        unsafe {
            if zig_ast_full_asm(tree, index, full_asm.as_mut_ptr()) {
                Some(full_asm.assume_init())
            } else {
                None
            }
        }
    }
}

unsafe extern "C" {
    fn zig_ast_full_asm(
        tree: *const Ast,
        index: NodeIndex,
        full_asm: *mut Asm,
    ) -> bool;
}

#[repr(C)]
pub struct Call<'ast> {
    pub ast: CallComponents<'ast>,
}

#[repr(C)]
pub struct CallComponents<'ast> {
    pub lparen: TokenIndex,
    pub fn_expr: NodeIndex,
    pub params_ptr: *const NodeIndex,
    pub params_len: usize,
    _marker: PhantomData<&'ast ()>,
}

impl<'ast> Full<'ast, 1> for Call<'ast> {
    unsafe fn from(
        tree: *const Ast,
        buffer: *mut [NodeIndex; 1],
        index: NodeIndex,
    ) -> Option<Self> {
        let mut full_call = MaybeUninit::uninit();
        unsafe {
            if zig_ast_full_call(tree, buffer, index, full_call.as_mut_ptr()) {
                Some(full_call.assume_init())
            } else {
                None
            }
        }
    }
}

unsafe extern "C" {
    fn zig_ast_full_call(
        tree: *const Ast,
        buffer: *mut [NodeIndex; 1],
        index: NodeIndex,
        full_call: *mut Call,
    ) -> bool;
}
